/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Lead = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
export const ProductView = IDL.Record({
  'id' : IDL.Text,
  'imageUrls' : IDL.Vec(IDL.Text),
  'tagline' : IDL.Text,
  'name' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'badge' : IDL.Text,
  'price' : IDL.Text,
});

export const idlService = IDL.Service({
  'addLead' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'adminLogin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'deleteProduct' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(ProductView)], ['query']),
  'getLead' : IDL.Func([IDL.Text], [Lead], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(ProductView)], ['query']),
  'seedProducts' : IDL.Func([IDL.Vec(ProductView)], [IDL.Bool], []),
  'updateProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
      ],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Lead = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const ProductView = IDL.Record({
    'id' : IDL.Text,
    'imageUrls' : IDL.Vec(IDL.Text),
    'tagline' : IDL.Text,
    'name' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'badge' : IDL.Text,
    'price' : IDL.Text,
  });
  
  return IDL.Service({
    'addLead' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'adminLogin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'deleteProduct' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(ProductView)], ['query']),
    'getLead' : IDL.Func([IDL.Text], [Lead], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(ProductView)], ['query']),
    'seedProducts' : IDL.Func([IDL.Vec(ProductView)], [IDL.Bool], []),
    'updateProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };