/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Lead = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });

export const idlService = IDL.Service({
  'addLead' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getLead' : IDL.Func([IDL.Text], [Lead], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Lead = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  
  return IDL.Service({
    'addLead' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getLead' : IDL.Func([IDL.Text], [Lead], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };