/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Lead { 'name' : string, 'email' : string }
export interface Product {
  'id' : string,
  'tagline' : string,
  'name' : string,
  'imageUrl' : string,
  'category' : string,
  'badge' : string,
  'price' : string,
}
export interface _SERVICE {
  'addLead' : ActorMethod<[string, string], undefined>,
  'addProduct' : ActorMethod<
    [string, string, string, string, string, string, string],
    undefined
  >,
  'adminLogin' : ActorMethod<[string], boolean>,
  'deleteProduct' : ActorMethod<[string], boolean>,
  'getAllLeads' : ActorMethod<[], Array<Lead>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getLead' : ActorMethod<[string], Lead>,
  'getProduct' : ActorMethod<[string], [] | [Product]>,
  'seedProducts' : ActorMethod<[Array<Product>], boolean>,
  'updateProduct' : ActorMethod<
    [string, string, string, string, string, string, string],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];